DROP MATERIALIZED VIEW IF EXISTS "public"."mv_agent_kpis";
CREATE MATERIALIZED VIEW "public"."mv_agent_kpis" AS
 SELECT f.user_id,
    f.month_start,
    f.year,
    f.month,
    f.month_name,
    f.role,
    p.job_title,
    p.full_name AS agent_name,
    p.email AS agent_email,
    f.target_visits,
    f.target_calls,
    f.target_reachability,
    f.target_quotations,
    f.target_orders,
    f.target_gmv,
    f.actual_visits,
    f.successful_visits,
    f.suspicious_visits,
    f.fraudulent_visits,
    f.cancelled_visits,
    f.avg_visit_duration_seconds,
    f.actual_calls,
    f.reachable_calls,
    f.actual_quotations,
    f.actual_orders,
    f.actual_gmv,
    f.unique_customers,
    f.new_customers,
    f.returning_customers,
    f.gross_profit,
    f.gross_margin,
    round(f.actual_visits::numeric / NULLIF(f.target_visits, 0)::numeric * 100::numeric, 2) AS visit_achievement_pct,
    round(f.actual_calls::numeric / NULLIF(f.target_calls, 0)::numeric * 100::numeric, 2) AS call_achievement_pct,
    round(f.actual_quotations::numeric / NULLIF(f.target_quotations, 0)::numeric * 100::numeric, 2) AS quotation_achievement_pct,
    NULL::numeric AS order_achievement_pct,
    round(f.actual_gmv / NULLIF(f.target_gmv, 0::numeric) * 100::numeric, 2) AS gmv_achievement_pct,
    round(f.reachable_calls::numeric / NULLIF(f.target_reachability, 0::numeric) * 100::numeric, 2) AS reachability_achievement_pct,
    round(f.actual_calls::numeric / NULLIF(f.actual_visits, 0)::numeric * 100::numeric, 2) AS call_to_visit_pct,
    round(f.actual_quotations::numeric / NULLIF(f.actual_visits, 0)::numeric * 100::numeric, 2) AS visit_to_quote_pct,
    round(f.actual_orders::numeric / NULLIF(f.actual_quotations, 0)::numeric * 100::numeric, 2) AS quote_to_order_pct,
    round(f.actual_orders::numeric / NULLIF(f.actual_calls, 0)::numeric * 100::numeric, 2) AS call_to_order_pct,
    f.actual_gmv / NULLIF(f.actual_visits, 0)::numeric AS gmv_per_visit,
    f.actual_gmv / NULLIF(f.actual_calls, 0)::numeric AS gmv_per_call,
    f.actual_orders::numeric / NULLIF(f.actual_visits, 0)::numeric AS orders_per_visit,
    f.actual_orders::numeric / NULLIF(f.actual_calls, 0)::numeric AS orders_per_call,
    f.actual_gmv / NULLIF(f.actual_orders, 0)::numeric AS avg_order_value,
    GREATEST(COALESCE(f.target_visits, 0::bigint) - f.actual_visits, 0::bigint) AS remaining_visits,
    GREATEST(COALESCE(f.target_calls, 0::bigint) - f.actual_calls, 0::bigint) AS remaining_calls,
    GREATEST(COALESCE(f.target_quotations, 0::bigint) - f.actual_quotations, 0::bigint) AS remaining_quotations,
    GREATEST(COALESCE(f.target_gmv, 0::numeric) - f.actual_gmv, 0::numeric) AS remaining_gmv
   FROM mv_agent_monthly_facts f
     LEFT JOIN profiles p ON p.id = f.user_id WITH NO DATA;
