CREATE TRIGGER app_download_links_set_updated_at BEFORE UPDATE ON public.app_download_links FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER audit_calls_changes AFTER INSERT OR DELETE OR UPDATE ON public.calls FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_customers_changes AFTER INSERT OR DELETE OR UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_dispatcher_activity_log_changes AFTER INSERT OR DELETE OR UPDATE ON public.dispatcher_activity_log FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_dispatcher_order_item_preparations_changes AFTER INSERT OR DELETE OR UPDATE ON public.dispatcher_order_item_preparations FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_dispatcher_order_preparations_changes AFTER INSERT OR DELETE OR UPDATE ON public.dispatcher_order_preparations FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_dispatcher_plan_item_preparations_changes AFTER INSERT OR DELETE OR UPDATE ON public.dispatcher_plan_item_preparations FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_dispatcher_plan_preparations_changes AFTER INSERT OR DELETE OR UPDATE ON public.dispatcher_plan_preparations FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_driver_cash_balance_changes AFTER INSERT OR DELETE OR UPDATE ON public.driver_cash_balance FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_driver_plan_collection_checks_changes AFTER INSERT OR DELETE OR UPDATE ON public.driver_plan_collection_checks FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_location_tracking_changes AFTER INSERT OR DELETE OR UPDATE ON public.location_tracking FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_collection_handovers_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_collection_handovers FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_collection_requests_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_collection_requests FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_delivery_plans_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_delivery_plans FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_driver_alerts_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_driver_alerts FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_order_collections_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_order_collections FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_return_shipment_items_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_return_shipment_items FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_route_settlements_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_route_settlements FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_route_tracking_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_route_tracking FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_shipment_collections_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_shipment_collections FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_shipment_events_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_shipment_events FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_shipment_items_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_shipment_items FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_shipment_status_history_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_shipment_status_history FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_logistics_shipments_changes AFTER INSERT OR DELETE OR UPDATE ON public.logistics_shipments FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_orders_changes AFTER INSERT OR DELETE OR UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER audit_visits_changes AFTER INSERT OR DELETE OR UPDATE ON public.visits FOR EACH ROW EXECUTE FUNCTION fn_audit_table_changes();
CREATE TRIGGER calls_set_odoo_insert_payload BEFORE INSERT OR UPDATE ON public.calls FOR EACH ROW EXECUTE FUNCTION set_calls_odoo_insert_payload();
CREATE TRIGGER calls_set_updated_at BEFORE UPDATE ON public.calls FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER competitor_intel_set_updated_at BEFORE UPDATE ON public.competitor_intel FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER create_order_intent_from_visit AFTER INSERT ON public.visits FOR EACH ROW EXECUTE FUNCTION create_order_intent_from_visit();
CREATE TRIGGER customers_refresh_logistics_shipment_route_data AFTER UPDATE OF lat, lng, customer_name, external_customer_id ON public.customers FOR EACH ROW WHEN (((old.lat IS DISTINCT FROM new.lat) OR (old.lng IS DISTINCT FROM new.lng) OR (old.customer_name IS DISTINCT FROM new.customer_name) OR (old.external_customer_id IS DISTINCT FROM new.external_customer_id))) EXECUTE FUNCTION logistics_refresh_customer_shipment_route_data();
CREATE TRIGGER customers_set_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER departments_set_updated_at BEFORE UPDATE ON public.departments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER dispatcher_order_item_preparations_set_updated_at BEFORE UPDATE ON public.dispatcher_order_item_preparations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER dispatcher_order_preparations_set_updated_at BEFORE UPDATE ON public.dispatcher_order_preparations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER dispatcher_plan_item_preparations_set_updated_at BEFORE UPDATE ON public.dispatcher_plan_item_preparations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER dispatcher_plan_preparations_set_updated_at BEFORE UPDATE ON public.dispatcher_plan_preparations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER dynamic_form_fields_set_updated_at BEFORE UPDATE ON public.dynamic_form_fields FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER finance_page_visibility_set_updated_at BEFORE UPDATE ON public.finance_page_visibility FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_collection_requests_set_updated_at BEFORE UPDATE ON public.logistics_collection_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_delivery_plans_set_updated_at BEFORE UPDATE ON public.logistics_delivery_plans FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_departments_set_updated_at BEFORE UPDATE ON public.logistics_departments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_driver_alerts_set_updated_at BEFORE UPDATE ON public.logistics_driver_alerts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_require_items_before_plan_start BEFORE INSERT OR UPDATE OF plan_status ON public.logistics_delivery_plans FOR EACH ROW EXECUTE FUNCTION logistics_prevent_itemless_active_plan();
CREATE TRIGGER logistics_shipment_collections_set_updated_at BEFORE UPDATE ON public.logistics_shipment_collections FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_shipment_items_set_updated_at BEFORE UPDATE ON public.logistics_shipment_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_shipments_complete_plan_after_delivery AFTER INSERT OR DELETE OR UPDATE OF plan_id, shipment_status ON public.logistics_shipments FOR EACH ROW EXECUTE FUNCTION private.logistics_shipments_complete_plan_after_delivery();
CREATE TRIGGER logistics_shipments_hydrate_route_data BEFORE INSERT OR UPDATE OF linked_order_id, customer_id, external_customer_id, warehouse_id, external_warehouse_id, warehouse_name, customer_latitude, customer_longitude, warehouse_latitude, warehouse_longitude ON public.logistics_shipments FOR EACH ROW EXECUTE FUNCTION logistics_hydrate_shipment_route_data();
CREATE TRIGGER logistics_shipments_set_updated_at BEFORE UPDATE ON public.logistics_shipments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_shipments_status_history AFTER UPDATE OF shipment_status ON public.logistics_shipments FOR EACH ROW EXECUTE FUNCTION logistics_record_shipment_status_history();
CREATE TRIGGER logistics_sync_watermarks_set_updated_at BEFORE UPDATE ON public.logistics_sync_watermarks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_users_set_updated_at BEFORE UPDATE ON public.logistics_users FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER logistics_warehouses_set_updated_at BEFORE UPDATE ON public.logistics_warehouses FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER notify_logistics_shipment_business_events AFTER INSERT OR UPDATE OF assigned_profile_id, delivery_phase, shipment_status ON public.logistics_shipments FOR EACH ROW EXECUTE FUNCTION notify_logistics_shipment_business_events();
CREATE TRIGGER notify_order_intent_created AFTER INSERT ON public.order_intents FOR EACH ROW EXECUTE FUNCTION notify_order_intent_created();
CREATE TRIGGER odoo_actions_set_updated_at BEFORE UPDATE ON public.odoo_actions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER odoo_crm_activity_dispatches_set_updated_at BEFORE UPDATE ON public.odoo_crm_activity_dispatches FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER on_profile_created_logistics_user AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION handle_new_logistics_profile();
CREATE TRIGGER order_delivery_documents_set_updated_at BEFORE UPDATE ON public.order_delivery_documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER order_intents_set_updated_at BEFORE UPDATE ON public.order_intents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER order_invoice_documents_set_updated_at BEFORE UPDATE ON public.order_invoice_documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER order_line_items_set_updated_at BEFORE UPDATE ON public.order_line_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER orders_set_odoo_insert_payload BEFORE INSERT OR UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION set_orders_odoo_insert_payload();
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER permission_catalog_set_updated_at BEFORE UPDATE ON public.permission_catalog FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER product_barcodes_set_updated_at BEFORE UPDATE ON public.product_barcodes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER products_dataset_set_updated_at BEFORE UPDATE ON public.products_dataset FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER products_set_odoo_insert_payload BEFORE INSERT OR UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION set_products_odoo_insert_payload();
CREATE TRIGGER products_set_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER quotations_set_updated_at BEFORE UPDATE ON public.quotations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER role_definitions_set_updated_at BEFORE UPDATE ON public.role_definitions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER sales_product_customer_mappings_set_updated_at BEFORE UPDATE ON public.sales_product_customer_mappings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER sales_targets_set_updated_at BEFORE UPDATE ON public.sales_targets FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER service_issues_set_updated_at BEFORE UPDATE ON public.service_issues FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_suplyd_products_live_updated_at BEFORE UPDATE ON public.suplyd_products_live FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_calls_set_user_uid BEFORE INSERT OR UPDATE OF user_id ON public.calls FOR EACH ROW EXECUTE FUNCTION calls_set_user_uid();
CREATE TRIGGER trg_customer_interactions_set_user_uid BEFORE INSERT OR UPDATE OF actor_user_id ON public.customer_interactions FOR EACH ROW EXECUTE FUNCTION customer_interactions_set_user_uid();
CREATE TRIGGER trg_finance_driver_settlements_updated_at BEFORE UPDATE ON public.finance_driver_settlements FOR EACH ROW EXECUTE FUNCTION set_finance_driver_settlements_updated_at();
CREATE TRIGGER trg_finance_invoices_updated_at BEFORE UPDATE ON public.finance_invoices FOR EACH ROW EXECUTE FUNCTION set_finance_invoices_updated_at();
CREATE TRIGGER trg_finance_payments_updated_at BEFORE UPDATE ON public.finance_payments FOR EACH ROW EXECUTE FUNCTION set_finance_payments_updated_at();
CREATE TRIGGER trg_normalize_display_type BEFORE INSERT OR UPDATE ON public.order_line_items FOR EACH ROW EXECUTE FUNCTION normalize_display_type();
CREATE TRIGGER trg_odoo_pending_actions_updated_at BEFORE UPDATE ON public.odoo_pending_actions FOR EACH ROW EXECUTE FUNCTION set_odoo_pending_action_updated_at();
CREATE TRIGGER trg_order_tickets_updated_at BEFORE UPDATE ON public.order_tickets FOR EACH ROW EXECUTE FUNCTION set_order_tickets_updated_at();
CREATE TRIGGER trg_orders_set_user_uid BEFORE INSERT OR UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION orders_set_user_uid();
CREATE TRIGGER trg_profiles_propagate_user_uid_to_calls AFTER UPDATE OF user_uid ON public.profiles FOR EACH ROW EXECUTE FUNCTION profiles_propagate_user_uid_to_calls();
CREATE TRIGGER trg_profiles_propagate_user_uid_to_customer_interactions AFTER UPDATE OF user_uid ON public.profiles FOR EACH ROW EXECUTE FUNCTION profiles_propagate_user_uid_to_customer_interactions();
CREATE TRIGGER trg_profiles_set_user_uid BEFORE INSERT OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION profiles_set_user_uid();
CREATE TRIGGER trg_sync_logistics_user_from_profile AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION sync_logistics_user_from_profile();
CREATE TRIGGER trg_visits_set_user_uid BEFORE INSERT OR UPDATE OF user_id ON public.visits FOR EACH ROW EXECUTE FUNCTION visits_set_user_uid();
CREATE TRIGGER trigger_update_driver_cash_balance_updated_at BEFORE UPDATE ON public.driver_cash_balance FOR EACH ROW EXECUTE FUNCTION update_driver_cash_balance_updated_at();
CREATE TRIGGER trigger_update_logistics_route_settlements_updated_at BEFORE UPDATE ON public.logistics_route_settlements FOR EACH ROW EXECUTE FUNCTION update_logistics_route_settlements_updated_at();
CREATE TRIGGER update_driver_plan_collection_checks_updated_at BEFORE UPDATE ON public.driver_plan_collection_checks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER update_driver_plan_settlement_requests_updated_at BEFORE UPDATE ON public.driver_plan_settlement_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER update_logistics_order_collections_updated_at BEFORE UPDATE ON public.logistics_order_collections FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER update_logistics_route_tracking_updated_at BEFORE UPDATE ON public.logistics_route_tracking FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER visit_note_translations_set_updated_at BEFORE UPDATE ON public.visit_note_translations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER visits_set_updated_at BEFORE UPDATE ON public.visits FOR EACH ROW EXECUTE FUNCTION set_updated_at();
