ALTER TABLE ONLY "kpi"."kpi_tracking" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "kpi"."kpi_tracking" ALTER COLUMN "source" SET DEFAULT 'manual'::text;
ALTER TABLE ONLY "kpi"."kpi_tracking" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "kpi"."kpi_tracking" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "kpi"."manual_upload_batches" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "kpi"."manual_upload_batches" ALTER COLUMN "row_count" SET DEFAULT 0;
ALTER TABLE ONLY "kpi"."manual_upload_batches" ALTER COLUMN "status" SET DEFAULT 'completed'::text;
ALTER TABLE ONLY "kpi"."manual_upload_batches" ALTER COLUMN "uploaded_at" SET DEFAULT now();
ALTER TABLE ONLY "kpi"."manual_upload_batches" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "kpi"."manual_values" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "kpi"."manual_values" ALTER COLUMN "uploaded_at" SET DEFAULT now();
ALTER TABLE ONLY "kpi"."manual_values" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "kpi"."odoo_values" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "kpi"."odoo_values" ALTER COLUMN "computed_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."app_download_links" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."app_download_links" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."app_download_links" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."app_download_links" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."app_download_links" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."audit_logs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."audit_logs" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."audit_logs" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "requires_urgent_action" SET DEFAULT false;
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "raw_form_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "source" SET DEFAULT 'manual'::text;
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "contact_status_details" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "objection_details" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "requested_actions" SET DEFAULT ARRAY[]::text[];
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "requested_action_details" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."calls" ALTER COLUMN "service_issue_flagged" SET DEFAULT false;
ALTER TABLE ONLY "public"."cart_items" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."cart_items" ALTER COLUMN "quantity" SET DEFAULT 1;
ALTER TABLE ONLY "public"."cart_items" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."cart_items" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."categories" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."categories" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."categories" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."categories" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."categories" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."competitor_intel" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."competitor_intel" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."competitor_intel" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."customer_interactions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."customer_interactions" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."customer_interactions" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "status" SET DEFAULT 'active'::record_status;
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "priority" SET DEFAULT 'medium'::customer_priority;
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "product_interests" SET DEFAULT '[]'::jsonb;
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "geofence_radius_meters" SET DEFAULT 150;
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "source" SET DEFAULT 'manual'::text;
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "last_sync_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."customers" ALTER COLUMN "has_product_classification" SET DEFAULT false;
ALTER TABLE ONLY "public"."department_role_assignments" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."departments" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."departments" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."departments" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."departments" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."dispatcher_activity_log" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."dispatcher_activity_log" ALTER COLUMN "entity_type" SET DEFAULT 'plan'::text;
ALTER TABLE ONLY "public"."dispatcher_activity_log" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_order_item_preparations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."dispatcher_order_item_preparations" ALTER COLUMN "requested_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."dispatcher_order_item_preparations" ALTER COLUMN "approved_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."dispatcher_order_item_preparations" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."dispatcher_order_item_preparations" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_order_item_preparations" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_order_preparations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."dispatcher_order_preparations" ALTER COLUMN "status" SET DEFAULT 'preparing'::text;
ALTER TABLE ONLY "public"."dispatcher_order_preparations" ALTER COLUMN "started_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_order_preparations" ALTER COLUMN "photos" SET DEFAULT '[]'::jsonb;
ALTER TABLE ONLY "public"."dispatcher_order_preparations" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_order_preparations" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_plan_item_preparations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."dispatcher_plan_item_preparations" ALTER COLUMN "total_requested_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."dispatcher_plan_item_preparations" ALTER COLUMN "approved_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."dispatcher_plan_item_preparations" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."dispatcher_plan_item_preparations" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_plan_item_preparations" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_plan_preparations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."dispatcher_plan_preparations" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."dispatcher_plan_preparations" ALTER COLUMN "started_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_plan_preparations" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."dispatcher_plan_preparations" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."driver_cash_balance" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."driver_cash_balance" ALTER COLUMN "cash_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."driver_cash_balance" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."driver_cash_balance" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."driver_cash_balance" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."driver_cash_balance" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."driver_plan_collection_checks" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."driver_plan_collection_checks" ALTER COLUMN "review_status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."driver_plan_collection_checks" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."driver_plan_collection_checks" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."driver_plan_settlement_requests" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."driver_plan_settlement_requests" ALTER COLUMN "total_debt_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."driver_plan_settlement_requests" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."driver_plan_settlement_requests" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."driver_plan_settlement_requests" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."driver_plan_settlement_requests" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."dynamic_form_field_options" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."dynamic_form_field_options" ALTER COLUMN "display_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."dynamic_form_field_options" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."dynamic_form_field_options" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."dynamic_form_fields" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."dynamic_form_fields" ALTER COLUMN "is_required" SET DEFAULT false;
ALTER TABLE ONLY "public"."dynamic_form_fields" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."dynamic_form_fields" ALTER COLUMN "display_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."dynamic_form_fields" ALTER COLUMN "validation_rules" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."dynamic_form_fields" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."dynamic_form_fields" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_accounts" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_accounts" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."finance_accounts" ALTER COLUMN "allow_posting" SET DEFAULT true;
ALTER TABLE ONLY "public"."finance_accounts" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_accounts" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_cost_centers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_cost_centers" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."finance_cost_centers" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "quantity" SET DEFAULT 1;
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "unit_price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "discount_percent" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "tax_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "line_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_note_lines" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "credit_note_date" SET DEFAULT CURRENT_DATE;
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "subtotal" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "discount_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "tax_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "status" SET DEFAULT 'draft'::text;
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."finance_credit_notes" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."finance_document_sequences" ALTER COLUMN "current_number" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_document_sequences" ALTER COLUMN "year_reset" SET DEFAULT true;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "commission_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "fuel_allowance" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "bonuses" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "penalties" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "cash_collected" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "cash_remitted" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "status" SET DEFAULT 'draft'::text;
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_driver_settlements" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_fiscal_periods" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_fiscal_periods" ALTER COLUMN "status" SET DEFAULT 'open'::text;
ALTER TABLE ONLY "public"."finance_fiscal_periods" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_invoice_lines" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_invoice_lines" ALTER COLUMN "quantity" SET DEFAULT 1;
ALTER TABLE ONLY "public"."finance_invoice_lines" ALTER COLUMN "unit_price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoice_lines" ALTER COLUMN "discount_pct" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoice_lines" ALTER COLUMN "line_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoice_lines" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoice_lines" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "status" SET DEFAULT 'draft'::text;
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "issue_date" SET DEFAULT CURRENT_DATE;
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "subtotal" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "tax_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "discount_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_invoices" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_journal_entries" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_journal_entries" ALTER COLUMN "status" SET DEFAULT 'posted'::text;
ALTER TABLE ONLY "public"."finance_journal_entries" ALTER COLUMN "posted_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."finance_journal_entries" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_journal_lines" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_journal_lines" ALTER COLUMN "debit" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_journal_lines" ALTER COLUMN "credit" SET DEFAULT 0;
ALTER TABLE ONLY "public"."finance_journal_lines" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."finance_journal_lines" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_journals" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_journals" ALTER COLUMN "type" SET DEFAULT 'general'::text;
ALTER TABLE ONLY "public"."finance_journals" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."finance_journals" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."finance_page_visibility" ALTER COLUMN "enabled" SET DEFAULT false;
ALTER TABLE ONLY "public"."finance_page_visibility" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_payments" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_payments" ALTER COLUMN "payment_date" SET DEFAULT CURRENT_DATE;
ALTER TABLE ONLY "public"."finance_payments" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."finance_payments" ALTER COLUMN "status" SET DEFAULT 'draft'::text;
ALTER TABLE ONLY "public"."finance_payments" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_payments" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."finance_tax_rates" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."finance_tax_rates" ALTER COLUMN "rate" SET DEFAULT 0.00;
ALTER TABLE ONLY "public"."finance_tax_rates" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."finance_tax_rates" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."kpi_manual_upload_batches" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."kpi_manual_upload_batches" ALTER COLUMN "row_count" SET DEFAULT 0;
ALTER TABLE ONLY "public"."kpi_manual_upload_batches" ALTER COLUMN "status" SET DEFAULT 'completed'::text;
ALTER TABLE ONLY "public"."kpi_manual_upload_batches" ALTER COLUMN "uploaded_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."kpi_manual_upload_batches" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."kpi_manual_values" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."kpi_manual_values" ALTER COLUMN "source_label" SET DEFAULT 'manual_upload'::text;
ALTER TABLE ONLY "public"."kpi_manual_values" ALTER COLUMN "uploaded_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."kpi_manual_values" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."location_tracking" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."location_tracking" ALTER COLUMN "captured_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."location_tracking" ALTER COLUMN "is_mocked" SET DEFAULT false;
ALTER TABLE ONLY "public"."location_tracking" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."location_tracking" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_collection_handovers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_collection_handovers" ALTER COLUMN "total_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_collection_handovers" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."logistics_collection_handovers" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_collection_handovers" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_collection_requests" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_collection_requests" ALTER COLUMN "collected_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_collection_requests" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."logistics_collection_requests" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."logistics_collection_requests" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_collection_requests" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_delivery_plans" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_delivery_plans" ALTER COLUMN "plan_reference" SET DEFAULT ('PLAN-'::text || upper(substr(replace((gen_random_uuid())::text, '-'::text, ''::text), 1, 10)));
ALTER TABLE ONLY "public"."logistics_delivery_plans" ALTER COLUMN "plan_status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."logistics_delivery_plans" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_delivery_plans" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_delivery_plans" ALTER COLUMN "route_metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_departments" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_departments" ALTER COLUMN "status" SET DEFAULT 'active'::record_status;
ALTER TABLE ONLY "public"."logistics_departments" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."logistics_departments" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_departments" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_departments" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_driver_alerts" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_driver_alerts" ALTER COLUMN "alert_type" SET DEFAULT 'sos'::text;
ALTER TABLE ONLY "public"."logistics_driver_alerts" ALTER COLUMN "status" SET DEFAULT 'open'::text;
ALTER TABLE ONLY "public"."logistics_driver_alerts" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_driver_alerts" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_driver_alerts" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "order_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "payment_method" SET DEFAULT 'cash'::text;
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "collected_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "collection_status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "driver_debt_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_order_collections" ALTER COLUMN "accounting_status" SET DEFAULT 'pending_accounting_review'::text;
ALTER TABLE ONLY "public"."logistics_return_shipment_items" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_return_shipment_items" ALTER COLUMN "received_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_return_shipment_items" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_return_shipment_items" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_route_settlements" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_route_settlements" ALTER COLUMN "total_cash_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_route_settlements" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."logistics_route_settlements" ALTER COLUMN "status" SET DEFAULT 'waiting_for_finance'::text;
ALTER TABLE ONLY "public"."logistics_route_settlements" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_route_settlements" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "planned_route" SET DEFAULT '[]'::jsonb;
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "actual_route" SET DEFAULT '[]'::jsonb;
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "vehicle_type" SET DEFAULT 'van'::text;
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "tracking_status" SET DEFAULT 'active'::text;
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "started_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_route_tracking" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "pending_delivery_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "collected_from_customer" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "collected_successfully_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "collection_status" SET DEFAULT 'pending_delivery_amount'::text;
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "payment_method" SET DEFAULT 'cash'::text;
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "driver_debt_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_collections" ALTER COLUMN "accounting_status" SET DEFAULT 'pending_accounting_review'::text;
ALTER TABLE ONLY "public"."logistics_shipment_events" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_shipment_events" ALTER COLUMN "payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_shipment_events" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "requested_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "done_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "reserved_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "forecast_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_shipment_items" ALTER COLUMN "returned_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_shipment_status_history" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_shipment_status_history" ALTER COLUMN "changed_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "shipment_state" SET DEFAULT 'draft'::text;
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "delivery_phase" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "shipment_status" SET DEFAULT 'PENDING_ASSIGN'::text;
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "route_locked" SET DEFAULT false;
ALTER TABLE ONLY "public"."logistics_shipments" ALTER COLUMN "is_return_shipment" SET DEFAULT false;
ALTER TABLE ONLY "public"."logistics_sync_watermarks" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_sync_watermarks" ALTER COLUMN "last_sync_row_count" SET DEFAULT 0;
ALTER TABLE ONLY "public"."logistics_sync_watermarks" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_users" ALTER COLUMN "status" SET DEFAULT 'active'::record_status;
ALTER TABLE ONLY "public"."logistics_users" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."logistics_users" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_users" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_users" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_vehicle_profiles" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_vehicle_profiles" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."logistics_warehouses" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."logistics_warehouses" ALTER COLUMN "status" SET DEFAULT 'active'::record_status;
ALTER TABLE ONLY "public"."logistics_warehouses" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."logistics_warehouses" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."logistics_warehouses" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."logistics_warehouses" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."notification_recipients" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."notification_recipients" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."notifications" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."notifications" ALTER COLUMN "channel" SET DEFAULT 'in_app'::notification_channel;
ALTER TABLE ONLY "public"."notifications" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."notifications" ALTER COLUMN "sent_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."notifications" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "description" SET DEFAULT ''::text;
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "http_method" SET DEFAULT 'POST'::text;
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "allowed_roles" SET DEFAULT ARRAY[]::app_role[];
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_actions" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_activity_dispatches" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_crm_activity_dispatches" ALTER COLUMN "attempt_count" SET DEFAULT 1;
ALTER TABLE ONLY "public"."odoo_crm_activity_dispatches" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_activity_dispatches" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_activity_reports" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_crm_activity_reports" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."odoo_crm_activity_reports" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."odoo_crm_activity_reports" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_activity_reports" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_lead_actions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_crm_lead_actions" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."odoo_crm_lead_actions" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "activity_ids" SET DEFAULT '{}'::text[];
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "expected_revenue" SET DEFAULT 0;
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "tag_ids" SET DEFAULT '{}'::text[];
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "tag_names" SET DEFAULT '{}'::text[];
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "active" SET DEFAULT true;
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_leads" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_model_records" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_crm_model_records" ALTER COLUMN "source" SET DEFAULT 'odoo_sync'::text;
ALTER TABLE ONLY "public"."odoo_crm_model_records" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."odoo_crm_model_records" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_crm_model_records" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."odoo_pending_action_audit_log" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_pending_action_audit_log" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."odoo_pending_actions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_pending_actions" ALTER COLUMN "odoo_method" SET DEFAULT 'create'::text;
ALTER TABLE ONLY "public"."odoo_pending_actions" ALTER COLUMN "payload_json" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."odoo_pending_actions" ALTER COLUMN "status" SET DEFAULT 'draft'::odoo_action_status;
ALTER TABLE ONLY "public"."odoo_pending_actions" ALTER COLUMN "retry_count" SET DEFAULT 0;
ALTER TABLE ONLY "public"."odoo_pending_actions" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."odoo_pending_actions" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."odoo_sync_rules" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."odoo_sync_rules" ALTER COLUMN "description_ar" SET DEFAULT ''::text;
ALTER TABLE ONLY "public"."odoo_sync_rules" ALTER COLUMN "operations" SET DEFAULT '{}'::text[];
ALTER TABLE ONLY "public"."odoo_sync_rules" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."odoo_sync_rules" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."odoo_sync_rules" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."onboarding_progress" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."onboarding_progress" ALTER COLUMN "current_step" SET DEFAULT 1;
ALTER TABLE ONLY "public"."onboarding_progress" ALTER COLUMN "completed" SET DEFAULT false;
ALTER TABLE ONLY "public"."onboarding_progress" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."onboarding_progress" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."order_cancellations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_cancellations" ALTER COLUMN "cancelled_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_cancellations" ALTER COLUMN "inventory_reversed" SET DEFAULT false;
ALTER TABLE ONLY "public"."order_cancellations" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_delivery_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_delivery_documents" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."order_delivery_documents" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_delivery_documents" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "priority" SET DEFAULT 'high'::text;
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "next_action" SET DEFAULT 'CREATE_ORDER_NOW'::text;
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "selected_customer_profiles" SET DEFAULT '[]'::jsonb;
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "source_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_intents" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_invoice_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_invoice_documents" ALTER COLUMN "amount_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_invoice_documents" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."order_invoice_documents" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."order_invoice_documents" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_invoice_documents" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "ordered_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "delivered_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "invoiced_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "unit_price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "discount_percent" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "subtotal_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "total_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_line_items" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_status_history" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_status_history" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_ticket_comments" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_ticket_comments" ALTER COLUMN "is_internal" SET DEFAULT false;
ALTER TABLE ONLY "public"."order_ticket_comments" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_tickets" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."order_tickets" ALTER COLUMN "status" SET DEFAULT 'open'::ticket_status;
ALTER TABLE ONLY "public"."order_tickets" ALTER COLUMN "priority" SET DEFAULT 'medium'::ticket_priority;
ALTER TABLE ONLY "public"."order_tickets" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."order_tickets" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "status" SET DEFAULT 'pending'::order_status;
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "source" SET DEFAULT 'external_sync'::text;
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "total_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "last_sync_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "shipping_address" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "payment_method" SET DEFAULT 'cash_on_delivery'::text;
ALTER TABLE ONLY "public"."orders" ALTER COLUMN "shipping_cost" SET DEFAULT 0;
ALTER TABLE ONLY "public"."permission_catalog" ALTER COLUMN "risk_level" SET DEFAULT 'medium'::text;
ALTER TABLE ONLY "public"."permission_catalog" ALTER COLUMN "is_navigation" SET DEFAULT false;
ALTER TABLE ONLY "public"."permission_catalog" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."permission_catalog" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."permission_catalog" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."permission_catalog" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."product_barcodes" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."product_barcodes" ALTER COLUMN "registration_source" SET DEFAULT 'dispatcher'::text;
ALTER TABLE ONLY "public"."product_barcodes" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."product_barcodes" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "currency" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "stock_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "low_stock_threshold" SET DEFAULT 5;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "track_inventory" SET DEFAULT true;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "status" SET DEFAULT 'draft'::text;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "is_featured" SET DEFAULT false;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "meta" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."product_catalog" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "stock_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "option_values" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."product_variants" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."products" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."products" ALTER COLUMN "average_cost" SET DEFAULT 0;
ALTER TABLE ONLY "public"."products" ALTER COLUMN "sales_price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."products" ALTER COLUMN "quantity_on_hand" SET DEFAULT 0;
ALTER TABLE ONLY "public"."products" ALTER COLUMN "incoming_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."products" ALTER COLUMN "outgoing_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."products" ALTER COLUMN "source" SET DEFAULT 'odoo_sheet'::text;
ALTER TABLE ONLY "public"."products" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."products" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."products" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."products_dataset" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."products_dataset" ALTER COLUMN "search_keywords" SET DEFAULT '[]'::jsonb;
ALTER TABLE ONLY "public"."products_dataset" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."products_dataset" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "role" SET DEFAULT 'sales_agent'::app_role;
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "status" SET DEFAULT 'active'::record_status;
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "prefer_otp" SET DEFAULT false;
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "password_enabled" SET DEFAULT true;
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "otp_enabled" SET DEFAULT false;
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "session_version" SET DEFAULT 1;
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."profiles" ALTER COLUMN "requires_password_change" SET DEFAULT false;
ALTER TABLE ONLY "public"."quotation_items" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."quotation_items" ALTER COLUMN "unit_price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."quotation_items" ALTER COLUMN "discount_percent" SET DEFAULT 0;
ALTER TABLE ONLY "public"."quotation_items" ALTER COLUMN "line_total" SET DEFAULT 0;
ALTER TABLE ONLY "public"."quotation_items" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."quotation_items" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "selected_company_ids" SET DEFAULT '[]'::jsonb;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "extra_discount_percent" SET DEFAULT 0;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "subtotal_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "discount_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "grand_total_amount" SET DEFAULT 0;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "currency_code" SET DEFAULT 'EGP'::text;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "show_grand_total" SET DEFAULT true;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "status" SET DEFAULT 'generated'::quotation_status;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "rendered_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "generated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."quotations" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."role_definitions" ALTER COLUMN "default_home_path" SET DEFAULT '/'::text;
ALTER TABLE ONLY "public"."role_definitions" ALTER COLUMN "is_management" SET DEFAULT false;
ALTER TABLE ONLY "public"."role_definitions" ALTER COLUMN "is_assignable" SET DEFAULT true;
ALTER TABLE ONLY "public"."role_definitions" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."role_definitions" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."role_definitions" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."role_permission_assignments" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_brand_mappings" ALTER COLUMN "example_products" SET DEFAULT '{}'::text[];
ALTER TABLE ONLY "public"."sales_brand_mappings" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_brand_mappings" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."sales_brand_mappings" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_customer_speciality_mappings" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_customer_speciality_mappings" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."sales_customer_speciality_mappings" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_customer_type_mappings" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_customer_type_mappings" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."sales_customer_type_mappings" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_product_category_mappings" ALTER COLUMN "sort_order" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_product_category_mappings" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."sales_product_category_mappings" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_product_customer_mappings" ALTER COLUMN "customer_specialities" SET DEFAULT '{}'::text[];
ALTER TABLE ONLY "public"."sales_product_customer_mappings" ALTER COLUMN "customer_types" SET DEFAULT '{}'::text[];
ALTER TABLE ONLY "public"."sales_product_customer_mappings" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."sales_product_customer_mappings" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_product_customer_mappings" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "target_visits" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "target_calls" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "target_reachability" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "target_gmv" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "target_quotations" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "working_days" SET DEFAULT 0;
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sales_targets" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."service_issues" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."service_issues" ALTER COLUMN "status" SET DEFAULT 'open'::text;
ALTER TABLE ONLY "public"."service_issues" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."service_issues" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sla_breaches" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."sla_breaches" ALTER COLUMN "breached_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sla_breaches" ALTER COLUMN "notified" SET DEFAULT false;
ALTER TABLE ONLY "public"."sla_breaches" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."sla_definitions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."sla_definitions" ALTER COLUMN "is_active" SET DEFAULT true;
ALTER TABLE ONLY "public"."sla_definitions" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."suplyd_products_history" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."suplyd_products_history" ALTER COLUMN "scraped_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."suplyd_products_live" ALTER COLUMN "last_scraped_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."suplyd_products_live" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."suplyd_products_live" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "started_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "status" SET DEFAULT 'running'::text;
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "products_fetched" SET DEFAULT 0;
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "products_upserted" SET DEFAULT 0;
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "products_with_cost" SET DEFAULT 0;
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."suplyd_scrape_batches" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."tenants" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."tenants" ALTER COLUMN "status" SET DEFAULT 'active'::text;
ALTER TABLE ONLY "public"."tenants" ALTER COLUMN "settings" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."tenants" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."tenants" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."user_device_sessions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."user_device_sessions" ALTER COLUMN "last_seen_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."user_device_sessions" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."visit_dynamic_answers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."visit_dynamic_answers" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."visit_note_translations" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "visit_mode" SET DEFAULT 'gps'::visit_mode;
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "checked_in_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "fraud_score" SET DEFAULT 0;
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "fraud_status" SET DEFAULT 'normal'::fraud_status;
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "fraud_signals" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "created_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "updated_at" SET DEFAULT timezone('utc'::text, now());
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "source" SET DEFAULT 'manual'::text;
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."visits" ALTER COLUMN "raw_form_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "product_name" SET DEFAULT ''::text;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "quantity_on_hand" SET DEFAULT 0;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "incoming_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "outgoing_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "reserved_quantity" SET DEFAULT 0;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "average_cost" SET DEFAULT 0;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "sales_price" SET DEFAULT 0;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "source" SET DEFAULT 'sync'::text;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "raw_payload" SET DEFAULT '{}'::jsonb;
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE ONLY "public"."warehouse_inventory" ALTER COLUMN "updated_at" SET DEFAULT now();
